# Generated by Django 5.2.1 on 2025-05-19 12:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(choices=[('Simple Sentence', 'Simple Sentences'), ('Tense', 'Tense'), ('Modal Part 1', 'Modal Part 1'), ('Modal Part 2', 'Modal Part 2'), ('Causative Verb', 'Causative Verb'), ('Voice', 'Voice'), ('Other', 'Other')], max_length=50)),
                ('main_content', django_ckeditor_5.fields.CKEditor5Field()),
                ('guidetion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
