# Generated by Django 5.2.1 on 2025-05-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
