# Generated by Django 5.2.1 on 2025-05-21 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDifficultVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficultwords', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedGrammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_sentence', models.BooleanField(default=False, verbose_name='Simple Sentence')),
                ('tense', models.BooleanField(default=False, verbose_name='Tense')),
                ('modal_part_1', models.BooleanField(default=False, verbose_name='Modal Part 1')),
                ('modal_part_2', models.BooleanField(default=False, verbose_name='Modal Part 2')),
                ('causative_verb', models.BooleanField(default=False, verbose_name='Causative Verb')),
                ('voice', models.BooleanField(default=False, verbose_name='Voice')),
                ('other', models.BooleanField(default=False, verbose_name='Other')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Grammar',
                'verbose_name_plural': 'Saved Grammar',
            },
        ),
        migrations.CreateModel(
            name='SavedVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserwordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worddefinition', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
