# Generated by Django 5.2.1 on 2025-05-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_userworddefinitions_delete_userworddefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedvocabulary',
            name='words',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userworddefinitions',
            name='definitions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
