# Generated by Django 5.2.1 on 2025-07-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_data", "0010_userdailydoubtsolving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdailydoubtsolving",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userdailymessageusage",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userdailystoryusage",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userfreetierstart",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
