# Generated by Django 5.2.1 on 2025-07-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_data", "0011_alter_userdailydoubtsolving_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdailydoubtsolving",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userdailymessageusage",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userdailystoryusage",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
