# Generated by Django 5.2.1 on 2025-09-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_data", "0012_alter_userdailydoubtsolving_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdailymessageusage",
            name="date",
            field=models.DateField(),
        ),
    ]
