# Generated by Django 5.2.1 on 2025-11-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_data", "0013_alter_userdailymessageusage_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdailystoryusage",
            name="date",
            field=models.DateField(),
        ),
    ]
