# Generated by Django 5.2.1 on 2025-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_number', models.PositiveIntegerField()),
                ('word_name', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('pronoun', 'Pronoun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('phrasal_verb', 'Phrasal Verb'), ('phrase', 'Phrase')], max_length=20)),
                ('hindi_meaning', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.CharField(max_length=255)),
                ('example', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
