# Generated by Django 5.2.1 on 2025-05-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vocabulary_level_alter_vocabulary_word_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'Noun'), ('pronoun', 'Pronoun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('phrasal_verb', 'Phrasal Verb'), ('phrase', 'Phrase'), ('question_word', 'Question_Word')], max_length=20),
        ),
    ]
