# Generated by Django 5.2.1 on 2025-05-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vocabulary_part_of_speech'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammarlesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='grammarlesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
