# Generated by Django 5.2.1 on 2025-11-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_grammarlesson_options_grammarlesson_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabulary",
            name="word_number",
            field=models.PositiveIntegerField(),
        ),
    ]
