import django
import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "faststart.settings")
django.setup()

from core.models import Vocabulary

# Choose a default level
DEFAULT_LEVEL = 'beginner'
vocab_list = [
    {
        "word_number": 493,
        "word_name": "speak up",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "ज़ोर से बोलना/खुलकर कहना",
        "definition": "To talk louder or express opinions boldly",
        "example": "The teacher asked the shy student to speak up during the debate competition./n शिक्षक ने शर्मीले छात्र से वाद-विवाद प्रतियोगिता के दौरान ज़ोर से बोलने को कहा।",
    },
    {
        "word_number": 494,
        "word_name": "be careful",
        "part_of_speech": "phrase",
        "hindi_meaning": "सावधान रहना",
        "definition": "To pay attention to avoid danger or mistakes",
        "example": "Be careful while crossing the busy Delhi roads - always use zebra crossings./n व्यस्त दिल्ली की सड़कों को पार करते समय सावधान रहें - हमेशा ज़ेबरा क्रॉसिंग का उपयोग करें।",
    },
    {
        "word_number": 495,
        "word_name": "be sure",
        "part_of_speech": "phrase",
        "hindi_meaning": "पक्का कर लेना",
        "definition": "To make certain about something",
        "example": "Be sure to check your train's platform number on the station display board./n स्टेशन के डिस्प्ले बोर्ड पर अपनी ट्रेन का प्लेटफॉर्म नंबर ज़रूर जांच लें।",
    },
    {
        "word_number": 496,
        "word_name": "so far",
        "part_of_speech": "phrase",
        "hindi_meaning": "अब तक",
        "definition": "Up to the present moment",
        "example": "So far in this cricket match, India has scored 250 runs with 3 wickets down./n इस क्रिकेट मैच में अब तक भारत ने 3 विकेट खोकर 250 रन बनाए हैं।",
    },
    {
        "word_number": 497,
        "word_name": "stay back",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "रुक जाना",
        "definition": "To remain in a place when others leave",
        "example": "Some students stay back after school for football practice in the ground./n कुछ छात्र स्कूल के बाद मैदान में फुटबॉल अभ्यास के लिए रुक जाते हैं।",
    },
    {
        "word_number": 498,
        "word_name": "try again",
        "part_of_speech": "phrase",
        "hindi_meaning": "फिर से कोशिश करना",
        "definition": "To attempt something another time",
        "example": "If you fail your driving test, don't worry - you can try again next month./n अगर आपका ड्राइविंग टेस्ट फेल हो जाता है, तो चिंता न करें - आप अगले महीने फिर से कोशिश कर सकते हैं।",
    },
    {
        "word_number": 499,
        "word_name": "take care of",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "ध्यान रखना",
        "definition": "To look after someone or something",
        "example": "Elderly grandparents often take care of grandchildren in Indian joint families./n भारतीय संयुक्त परिवारों में बुजुर्ग दादा-दादी अक्सर पोते-पोतियों का ध्यान रखते हैं।",
    },
    {
        "word_number": 500,
        "word_name": "take part",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "भाग लेना",
        "definition": "To participate in an activity",
        "example": "Many schools encourage students to take part in Republic Day cultural programs./n कई स्कूल छात्रों को गणतंत्र दिवस के सांस्कृतिक कार्यक्रमों में भाग लेने के लिए प्रोत्साहित करते हैं।",
    },
    {
        "word_number": 501,
        "word_name": "put off",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "टालना",
        "definition": "To postpone or delay something",
        "example": "Don't put off your science project until the last day before submission./n अपना विज्ञान प्रोजेक्ट जमा करने से ठीक पहले वाले दिन तक के लिए मत टालें।",
    },
    {
        "word_number": 502,
        "word_name": "save up",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "बचत करना",
        "definition": "To keep money for future use",
        "example": "Children in India often save up their pocket money to buy festival fireworks./n भारत में बच्चे अक्सर त्योहारों पर पटाखे खरीदने के लिए अपनी जेबखर्च बचाते हैं।",
    },
    {
        "word_number": 503,
        "word_name": "shut down",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "बंद करना",
        "definition": "To close a business or turn off a machine",
        "example": "Many small shops shut down during afternoon hours in hot summer months./n गर्मी के महीनों में दोपहर के समय कई छोटी दुकानें बंद कर देती हैं।",
    },
    {
        "word_number": 504,
        "word_name": "sign in",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "प्रवेश दर्ज करना",
        "definition": "To register arrival at a place",
        "example": "Visitors must sign in at the security desk before entering corporate offices./n आगंतुकों को कॉर्पोरेट कार्यालयों में प्रवेश करने से पहले सुरक्षा डेस्क पर प्रवेश दर्ज करना होगा।",
    },
    {
        "word_number": 505,
        "word_name": "sign out",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "निकास दर्ज करना",
        "definition": "To register departure from a place",
        "example": "Students must sign out in the register when leaving school premises early./n जल्दी स्कूल परिसर छोड़ते समय छात्रों को रजिस्टर में निकास दर्ज करना होगा।",
    },
    {
        "word_number": 506,
        "word_name": "slow down",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "गति कम करना",
        "definition": "To reduce speed",
        "example": "Drivers must slow down near school zones for children's safety./n बच्चों की सुरक्षा के लिए चालकों को स्कूल क्षेत्र के निकट गति कम करनी चाहिए।",
    },
    {
        "word_number": 507,
        "word_name": "look out",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "ध्यान देना",
        "definition": "To be watchful or careful",
        "example": "Look out for pickpockets in crowded market places during festival season./n त्योहार के मौसम में भीड़-भाड़ वाले बाजार स्थानों पर जेबकतरों से सावधान रहें।",
    },
    {
        "word_number": 508,
        "word_name": "check in",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "पंजीकरण करना",
        "definition": "To register arrival (at hotel/airport)",
        "example": "Passengers should check in at least 2 hours before domestic flights in India./n यात्रियों को भारत में घरेलू उड़ानों से कम से कम 2 घंटे पहले पंजीकरण करना चाहिए।",
    },
    {
        "word_number": 509,
        "word_name": "fancy",
        "part_of_speech": "adjective",
        "hindi_meaning": "अलंकृत/विशिष्ट",
        "definition": "Elaborate or sophisticated",
        "example": "Youngsters often save money to eat at fancy restaurants on special occasions./n युवा अक्सर विशेष अवसरों पर अलंकृत रेस्तरां में खाने के लिए पैसे बचाते हैं।",
    },
    {
        "word_number": 510,
        "word_name": "excited",
        "part_of_speech": "adjective",
        "hindi_meaning": "उत्साहित",
        "definition": "Very enthusiastic and eager",
        "example": "Children get excited when they see the first rain after hot summer./n बच्चे उत्साहित हो जाते हैं जब वे गर्म गर्मी के बाद पहली बारिश देखते हैं।",
    },
    {
        "word_number": 511,
        "word_name": "guilty",
        "part_of_speech": "adjective",
        "hindi_meaning": "दोषी",
        "definition": "Responsible for wrongdoing",
        "example": "He felt guilty for forgetting his best friend's birthday./n वह अपने सबसे अच्छे दोस्त का जन्मदिन भूलने के लिए दोषी महसूस करता था।",
    },
    {
        "word_number": 512,
        "word_name": "nearly",
        "part_of_speech": "adverb",
        "hindi_meaning": "लगभग",
        "definition": "Almost but not completely",
        "example": "We were nearly late for the movie because of heavy traffic near the mall./n मॉल के पास भारी यातायात के कारण हम फिल्म के लिए लगभग लेट हो गए थे।",
    },
    {
        "word_number": 513,
        "word_name": "neat",
        "part_of_speech": "adjective",
        "hindi_meaning": "साफ-सुथरा",
        "definition": "Tidy and in order",
        "example": "Indian mothers always keep their kitchens neat and clean./n भारतीय माताएँ हमेशा अपने रसोईघर को साफ-सुथरा रखती हैं।",
    },
    {
        "word_number": 514,
        "word_name": "jolly",
        "part_of_speech": "adjective",
        "hindi_meaning": "खुशमिज़ाज",
        "definition": "Happy and cheerful",
        "example": "The jolly uncle always brings sweets for children during family gatherings./n खुशमिज़ाज चाचा परिवार के समारोहों के दौरान हमेशा बच्चों के लिए मिठाई लाते हैं।",
    },
    {
        "word_number": 515,
        "word_name": "ducks",
        "part_of_speech": "noun",
        "hindi_meaning": "बतख",
        "definition": "Water birds with short legs and webbed feet",
        "example": "Children enjoy feeding bread to ducks in city ponds during winter./n सर्दियों में बच्चे शहर के तालाबों में बतखों को रोटी खिलाने का आनंद लेते हैं।",
    },
    {
        "word_number": 516,
        "word_name": "goats",
        "part_of_speech": "noun",
        "hindi_meaning": "बकरियाँ",
        "definition": "Horned animals often kept for milk or meat",
        "example": "Villagers in Rajasthan often keep goats for their livelihood./n राजस्थान के ग्रामीण अक्सर अपनी आजीविका के लिए बकरियाँ पालते हैं।",
    },
    {
        "word_number": 517,
        "word_name": "hens",
        "part_of_speech": "noun",
        "hindi_meaning": "मुर्गियाँ",
        "definition": "Female chickens kept for eggs or meat",
        "example": "Many rural households in India keep hens in their backyard for fresh eggs./n भारत के कई ग्रामीण घरों में ताज़े अंडों के लिए आंगन में मुर्गियाँ पाली जाती हैं।",
    },
    {
        "word_number": 518,
        "word_name": "owls",
        "part_of_speech": "noun",
        "hindi_meaning": "उल्लू",
        "definition": "Nocturnal birds with large eyes",
        "example": "Owls are considered wise in stories but bring bad luck in some Indian superstitions./n कहानियों में उल्लू को बुद्धिमान माना जाता है लेकिन कुछ भारतीय अंधविश्वासों में यह अशुभ होता है।",
    },
    {
        "word_number": 519,
        "word_name": "pigeons",
        "part_of_speech": "noun",
        "hindi_meaning": "कबूतर",
        "definition": "Plump birds often seen in cities",
        "example": "People feed grains to pigeons near temples across India./n लोग भारत भर में मंदिरों के पास कबूतरों को अनाज खिलाते हैं।",
    },
    {
        "word_number": 520,
        "word_name": "puppies",
        "part_of_speech": "noun",
        "hindi_meaning": "पिल्ले",
        "definition": "Baby dogs",
        "example": "The street dog gave birth to cute puppies near our society garden./n सड़क कुत्ती ने हमारे सोसाइटी के बगीचे के पास प्यारे पिल्लों को जन्म दिया।",
    },
    {
        "word_number": 521,
        "word_name": "sheep",
        "part_of_speech": "noun",
        "hindi_meaning": "भेड़",
        "definition": "Woolly animals kept in flocks",
        "example": "Shepherds in Himachal Pradesh graze sheep on mountain slopes./n हिमाचल प्रदेश में गड़रिए पहाड़ी ढलानों पर भेड़ चराते हैं।",
    },
    {
        "word_number": 522,
        "word_name": "pig",
        "part_of_speech": "noun",
        "hindi_meaning": "सूअर",
        "definition": "Pink farm animal with short legs",
        "example": "In some Indian villages, pigs are reared near garbage dumping areas./n कुछ भारतीय गाँवों में, सूअरों को कचरा डंपिंग क्षेत्रों के पास पाला जाता है।",
    },
    {
        "word_number": 523,
        "word_name": "peacock",
        "part_of_speech": "noun",
        "hindi_meaning": "मोर",
        "definition": "India's national bird with colorful feathers",
        "example": "The peacock danced beautifully when it started raining in the village./n गाँव में बारिश शुरू होते ही मोर सुंदरता से नाचने लगा।",
    },
    {
        "word_number": 524,
        "word_name": "flies",
        "part_of_speech": "noun",
        "hindi_meaning": "मक्खियाँ",
        "definition": "Small flying insects",
        "example": "During summer, food should be covered to protect it from flies./n गर्मियों में भोजन को मक्खियों से बचाने के लिए ढक कर रखना चाहिए।",
    },
    {
        "word_number": 525,
        "word_name": "frogs",
        "part_of_speech": "noun",
        "hindi_meaning": "मेंढक",
        "definition": "Small jumping amphibians that live in water",
        "example": "After monsoon rains, frogs croak loudly in village ponds./n मानसून की बारिश के बाद, गाँव के तालाबों में मेंढक जोर-जोर से टर्राते हैं।",
    },
    {
        "word_number": 526,
        "word_name": "lane",
        "part_of_speech": "noun",
        "hindi_meaning": "गली",
        "definition": "Narrow road or path",
        "example": "The sweet shop in the narrow lane behind the temple is famous for its jalebis./n मंदिर के पीछे की संकरी गली में मिठाई की दुकान अपने जलेबियों के लिए प्रसिद्ध है।",
    },
    {
        "word_number": 527,
        "word_name": "pane",
        "part_of_speech": "noun",
        "hindi_meaning": "शीशे का टुकड़ा",
        "definition": "Sheet of glass in a window",
        "example": "The cricket ball broke the window pane of our neighbor's house./n क्रिकेट की गेंद ने हमारे पड़ोसी के घर की खिड़की का शीशा तोड़ दिया।",
    },
    {
        "word_number": 528,
        "word_name": "edge",
        "part_of_speech": "noun",
        "hindi_meaning": "किनारा",
        "definition": "The outside limit of an object",
        "example": "Don't sit on the edge of the bed or you might fall down./n बिस्तर के किनारे मत बैठो नहीं तो तुम गिर सकते हो।",
    },
    {
        "word_number": 529,
        "word_name": "walk in",
        "part_of_speech": "phrasal_verb",
        "hindi_meaning": "अंदर चलकर आना",
        "definition": "To enter a place by walking",
        "example": "You can't just walk in the principal's office without knocking first./n आप बिना दरवाज़ा खटखटाए प्रधानाचार्य के कार्यालय में अंदर नहीं जा सकते।",
    },
    {
        "word_number": 530,
        "word_name": "dash",
        "part_of_speech": "verb",
        "hindi_meaning": "तेज़ी से भागना",
        "definition": "To run or travel quickly",
        "example": "When it started raining, people dashed for shelter at nearby shops./n जब बारिश शुरू हुई, तो लोग पास की दुकानों में आश्रय लेने के लिए तेज़ी से भागे।",
    },
]
objects = []

for vocab in vocab_list:
    vocab["level"] = DEFAULT_LEVEL
    obj = Vocabulary(**vocab)
    objects.append(obj)

Vocabulary.objects.bulk_create(objects, ignore_conflicts=True)
print(f"{len(objects)} vocabulary items inserted.")
